# SPDX-License-Identifier: GPL-3.0-or-later
# {{ template_destpath }}
# {{ ansible_managed }}

{% include "Containerfile.core.j2" %}

FROM base_image AS build
RUN apk add --no-cache --upgrade build-base git libffi-dev libpq-dev python3-dev py3-wheel
RUN python3 -m venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN pip --disable-pip-version-check --no-cache-dir install \
    git+{{ capstone_source_mirror }}/placement@stable/{{ capstone_release | lower }}

FROM base_image AS release
RUN apk add --no-cache --upgrade libpq python3
RUN mkdir -p /etc/placement /var/log/placement
RUN addgroup placement && adduser -DHS -G placement placement
COPY --chown=placement:placement --from=build /opt/.venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
USER placement
