# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Build container image
  containers.podman.podman_image:
    name: capstone/redis
    path: /etc/capstone/redis
    state: present
    tag: "{{ capstone_release | lower }}"
    build:
      annotation:
        app: redis
        info: Redis
    force: true
