# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Build container image
  containers.podman.podman_image:
    name: capstone/openstackclient
    path: /etc/capstone/openstackclient
    state: present
    tag: "{{ openstack_release | lower }}"
    build:
      annotation:
        app: openstackclient
        info: OpenStack Client
    force: true
