# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Prepare
  hosts: all
  tags: [always]
  tasks:
    - name: Find all playbook roles
      ansible.builtin.find:
        file_type: directory
        paths: "{{ playbook_dir }}/roles"
      delegate_to: localhost
      register: playbook_roles

    - name: Include defaults from playbook roles
      ansible.builtin.include_vars: "{{ item.path }}/defaults/main.yaml"
      loop: "{{ playbook_roles.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

- name: Depends
  hosts: all
  tags: [depends]
  roles:
    - role: capstone.ceph
      tags: [ceph]

    - role: capstone.postgres
      tags: [postgres]

    - role: capstone.rabbitmq
      tags: [rabbitmq]

    - role: capstone.redis
      tags: [redis]

- name: OS Core
  hosts: all
  tags: [os-core]
  roles:
    - role: capstone.keystone
      tags: [keystone]

    - role: capstone.glance
      tags: [glance]

    - role: capstone.placement
      tags: [placement]

    - role: capstone.nova
      tags: [nova]

    - role: capstone.neutron
      tags: [neutron]

    - role: capstone.cinder
      tags: [cinder]

    # capstone.horizon must be the last role in this play
    - role: capstone.horizon
      tags: [horizon]

- name: OS Extras
  hosts: all
  tags: [os-extras]
  roles:
    - role: capstone.openstackclient
      tags: [openstackclient]

    - role: capstone.tempest
      tags: [tempest]
