# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Prepare
  hosts: all
  tags: [always]
  tasks:
    - name: Find all playbook roles
      ansible.builtin.find:
        file_type: directory
        paths: "{{ playbook_dir }}/roles"
      delegate_to: localhost
      register: playbook_roles

    - name: Include defaults from playbook roles
      ansible.builtin.include_vars: "{{ item.path }}/defaults/main.yml"
      loop: "{{ playbook_roles.files }}"
      loop_control:
        label: "{{ item.path | basename }}"

- name: Depends
  hosts: all
  tags: [depends]
  roles:
    - { role: setup, tags: [setup] }
    - { role: cephadm, tags: [ceph] }
    - { role: postgres, tags: [postgres] }
    - { role: redis, tags: [redis] }

- name: OpenStack
  hosts: all
  tags: [openstack]
  roles:
    # OpenStack core
    - { role: keystone, tags: [keystone] }
    - { role: glance, tags: [glance] }
    - { role: placement, tags: [placement] }
    - { role: nova, tags: [nova] }
    - { role: neutron, tags: [neutron] }
    - { role: cinder, tags: [cinder] }

    # horizon must be the last role in this play so that Horizon dashboards for
    # all services are installed
    - { role: horizon, tags: [horizon] }
