# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Build container image
  containers.podman.podman_image:
    name: capstone/neutron
    path: /etc/capstone/neutron
    state: present
    tag: "{{ openstack_release | lower }}"
    build:
      annotation:
        app: neutron
        info: OpenStack Neutron
    force: true
