# SPDX-License-Identifier: GPL-3.0-or-later
# {{ template_destpath }}
# {{ ansible_managed }}

{% include "Containerfile.core.j2" %}

FROM base_image AS build
RUN apk add --no-cache --upgrade build-base git libffi-dev libpq-dev python3-dev py3-wheel
RUN python3 -m venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN pip --disable-pip-version-check --no-cache-dir install \
    git+{{ capstone_source_mirror }}/python-openstackclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-barbicanclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-cinderclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-designateclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-glanceclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-keystoneclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-neutronclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-novaclient@stable/{{ capstone_release | lower }} \
    git+{{ capstone_source_mirror }}/python-swiftclient@stable/{{ capstone_release | lower }}

FROM base_image AS release
RUN apk add --no-cache --upgrade libpq python3
RUN mkdir -p /etc/openstackclient /var/log/openstackclient
RUN addgroup openstackclient && adduser -DHS -G openstackclient openstackclient
COPY --chown=openstackclient:openstackclient --from=build /opt/.venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN mkdir -p /etc/openstackclient
USER openstackclient
