# {{ template_destpath }}
# {{ ansible_managed }}

FROM {{ openstack_container_image }} AS core
RUN apk --no-cache add apache2-mod-wsgi py3-psycopg2 python3 tini tzdata
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
ENTRYPOINT ["/sbin/tini", "--"]

FROM core AS build
RUN apk --no-cache add build-base git libffi-dev libpq-dev python3-dev py3-wheel
RUN python3 -m venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN pip --disable-pip-version-check --no-cache-dir install \
    git+{{ openstack_mirror }}/keystone@stable/{{ openstack_release | lower }}

FROM core AS release
RUN mkdir -p /etc/keystone /var/log/keystone
RUN addgroup keystone
RUN adduser -DHS -G keystone keystone
COPY --chown=keystone:keystone ./keystone.conf /etc/keystone/keystone.conf
COPY --chown=keystone:keystone ./entrypoint.sh /usr/local/bin/entrypoint.sh
COPY --chown=keystone:keystone --from=build /opt/.venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
USER keystone
CMD ["/bin/sh", "entrypoint.sh"]
