# {{ template_destpath }}
# {{ ansible_managed }}

FROM {{ openstack_container_image }} AS core
RUN apk --no-cache add libxslt py3-psycopg2 python3 tini tzdata
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
ENTRYPOINT ["/sbin/tini", "--"]

FROM core AS build
RUN apk --no-cache add build-base git libffi-dev libpq-dev libxslt-dev python3-dev py3-wheel
RUN python3 -m venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN pip --disable-pip-version-check --no-cache-dir install \
    git+{{ openstack_mirror }}/cinder@stable/{{ openstack_release | lower }}

FROM core AS release
RUN mkdir -p /etc/cinder /var/log/cinder
RUN addgroup cinder
RUN adduser -DHS -G cinder cinder
COPY --chown=cinder:cinder --from=build /opt/.venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
USER cinder
