# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Build container image
  containers.podman.podman_image:
    name: capstone/redis
    path: /etc/capstone/redis
    state: present
    tag: "{{ openstack_release | lower }}"
    build:
      annotation:
        app: redis
        info: OpenStack redis
      force_rm: true
    force: >-
      {{ true if redis_config is defined and redis_config.changed|bool
      else false }}
