# {{ template_destpath }}
# {{ ansible_managed }}

FROM {{ openstack_container_image }} AS core
RUN apk --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing add rabbitmq-server
RUN apk --no-cache add python3 rabbitmq-server tini tzdata
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
ENTRYPOINT ["/sbin/tini", "--"]

FROM core AS release
USER rabbitmq
