# SPDX-License-Identifier: GPL-3.0-or-later
# {{ template_destpath }}
# {{ ansible_managed }}

{% include "Containerfile.core.j2" %}

FROM base_image AS build
RUN apk add --no-cache --upgrade build-base git libffi-dev libpq-dev python3-dev py3-wheel
RUN python3 -m venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN pip --disable-pip-version-check --no-cache-dir install \
    git+{{ capstone_source_mirror }}/tempest@30.1.0

FROM base_image AS release
RUN apk add --no-cache --upgrade libpq python3
RUN mkdir -p /etc/tempest /var/log/tempest
RUN addgroup tempest && adduser -DHS -G tempest tempest
COPY --chown=tempest:tempest --from=build /opt/.venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
USER tempest
