# {{ template_destpath }}
# {{ ansible_managed }}

FROM {{ openstack_container_image }} AS core
RUN apk --no-cache add py3-psycopg2 python3 tini tzdata
RUN ln -sf /usr/share/zoneinfo/UTC /etc/localtime
ENTRYPOINT ["/sbin/tini", "--"]

FROM core AS build
RUN apk --no-cache add build-base git libffi-dev libpq-dev python3-dev py3-wheel
RUN python3 -m venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN pip --disable-pip-version-check --no-cache-dir install \
    git+{{ openstack_mirror }}/python-openstackclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-barbicanclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-cinderclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-designateclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-glanceclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-keystoneclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-neutronclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-novaclient@stable/{{ openstack_release | lower }} \
    git+{{ openstack_mirror }}/python-swiftclient@stable/{{ openstack_release | lower }}

FROM core AS release
RUN mkdir -p /etc/openstackclient /var/log/openstackclient
RUN addgroup openstackclient
RUN adduser -DHS -G openstackclient openstackclient
COPY --chown=openstackclient:openstackclient --from=build /opt/.venv /opt/.venv
ENV PATH="/opt/.venv/bin:$PATH"
RUN mkdir -p /etc/openstackclient
USER openstackclient
